name: consent_kit_example
description: Example app for consent_kit.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.0.0
  consent_kit:
    path: ../

flutter:
  uses-material-design: true
